[tool.poetry]
name = "shopping-cart"
version = "0.1.0"
description = ""
authors = ["Karan Jain <karan.jain@wegift.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
